### ISSUE TITLE
Seeing 'NANANA' in some records pad_bbl field

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-geosearch-pad-normalize#54]
some records have a `pad_bbl` field with value 'NANANA', we should make sure that the output from this script only includes rows with a valid 10-character BBL in `pad_bbl`

**Comment by allthesignals** [comment]
These are the offending lines: 
https://github.com/NYCPlanning/labs-geosearch-pad-normalize/blob/develop/_clean.R#L12-L17

The problem is that although the lot is supposed to be a special condo type (which means it has some adjustments to its BBL), the `billboro`, `billlot`, `billblock` values weren't found for those particular rows (about 3500, before expansion step). So it gets `NANANA`. There are two paths forward:

 - Default back to BBL when the billlot info is not found
 - Investigate why those joins aren't being made. 

Currently, about 33,000 rows properly join the bill BBL data.
